name: Build Tailwind CSS
on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build CSS (minified)
        run: npm run build:css

      - name: Commit built assets (styles.css + lockfile)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/styles.css
            if [ -f package-lock.json ]; then git add package-lock.json; fi
            git commit -m "build: update compiled Tailwind CSS"
            git push
          fi
